services:

  supplier:
    image: supplier:v1.0
    build:
      context: ./
      dockerfile: ./supplier/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task-1-db

  consumer:
    image: consumer:v1.0
    build:
      context: ./
      dockerfile: ./consumer/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - supplier
    environment:
      - SUPPLIER_URL=http://localhost:8080/api/v1/



  postgres:
    container_name: postgres_consumer
    image: postgres
    environment:
      POSTGRES_DB: task-1-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - t1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  t1: